version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - 8000:8000
    working_dir: /var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: toolingdb
      MYSQL_USER: john
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db:
