version: "3.9"
services:
  tooling_frontend:
    build: .
    ports:
      - 8000:8000
    working_dir: /var/www/html
    links:
      - data
    depends_on:
      - data
  data:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
volumes:
  tooling_frontend:
  db:
